### 获取文件 chunk info
POST http://localhost:8787/files/chunks
Content-Type: application/json

{
  "sha": "1212",
  "uuid": "2323",
  "size": 5464,
  "chunks": [
    {
      "chunkId": 0,
      "size": 5464
    }
  ]
}
###